# Generated by Django 4.2.21 on 2025-05-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pdf", models.FileField(upload_to="forms/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
